sudo: required
services:
  - docker

before_install:
  - docker build -t palakgupta/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true palakgupta/react-test npm test

after_success:
  - docker build -t palakgupta/multi-client ./client
  - docker build -t palakgupta/multi-nginx  ./nginx
  - docker build -t palakgupta/multi-server ./server
  - docker build -t palakgupta/mutli-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push palakgupta/multi-client
  - docker push palakgupta/multi-nginx
  - docker push palakgupta/multi-server
  - docker push palakgupta/multi-worker

