sudo: required
services:
  - docker

before_install:
  - docker build -t palak147/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true palak147/react-test npm run test -- --coverage

after_success:
  - docker build -t palak147/multi-client ./client
  - docker build -t palak147/multi-nginx  ./nginx
  - docker build -t palak147/multi-server ./server
  - docker build -t palak147/multi-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #Take those images and push them to docker hub
  - docker push palak147/multi-client
  - docker push palak147/multi-nginx
  - docker push palak147/multi-server
  - docker push palak147/multi-worker

